<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="3872" started-at="2020-03-31T12:31:58Z" finished-at="2020-03-31T12:32:02Z">
    <groups>
    </groups>
    <test name="Check logs" duration-ms="3872" started-at="2020-03-31T12:31:58Z" finished-at="2020-03-31T12:32:02Z">
      <class name="tests.jsErrorTest">
        <test-method status="PASS" signature="beforeTest(java.lang.String)[pri:0, instance:tests.jsErrorTest@29774679]" name="beforeTest" is-config="true" duration-ms="1726" started-at="2020-03-31T15:31:58Z" finished-at="2020-03-31T15:32:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Check logs]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="jsErrorTest()[pri:0, instance:tests.jsErrorTest@29774679]" name="jsErrorTest" duration-ms="2129" started-at="2020-03-31T15:32:00Z" finished-at="2020-03-31T15:32:02Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:some fail of test,JS error is found http://the-internet.herokuapp.com/javascript_error 6:51 Uncaught TypeError: Cannot read property 'xyz' of undefined]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:some fail of test,JS error is found http://the-internet.herokuapp.com/javascript_error 6:51 Uncaught TypeError: Cannot read property 'xyz' of undefinedat org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at tests.jsErrorTest.jsErrorTest(jsErrorTest.java:45)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- jsErrorTest -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:tests.jsErrorTest@29774679]" name="closeBrowser" is-config="true" duration-ms="1" started-at="2020-03-31T15:32:02Z" finished-at="2020-03-31T15:32:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- tests.jsErrorTest -->
    </test> <!-- Check logs -->
  </suite> <!-- Suite -->
</testng-results>
